<?php   
include "top.php";
?>

        <span class="">
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span class="" style="font-family: garamond">Lauren Hayes (QUEENIE) </span></b><span style="font-family: garamond">is a junior majoring in Chemistry and is absolutely thrilled to be participating in her second Ram&#8217;s Head production. She recently made her Stanford theatrical debut in Ram&#8217;s Head&#8217;s Winter One Acts <i style="mso-bidi-font-style: normal">The Ladies&#8217; Apocalypse</i> (Emma Currest). During her first two years at Stanford, she performed with the a cappella group Mixed Company as an alto. She would like to thank Barrett and Cynthia for putting her in silver sequins, Mr. Ossola for training and inspiration, and her family for their endless love, patience, and encouragement.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Charlton Gholson (BURRS)</span></b><span style="font-family: garamond"> is excited to make his theatrical debut with the talented cast of <i>The Wild Party</i>.&nbsp; A junior from Houston, TX, Charlton spent his first two years at Stanford in the Fleet Street Singers, and was attracted to <i>The Wild Party</i> the moment he first heard the score.&nbsp; He would like to thank the amazing cast and crew, as well as his friends and family for their never-ending love and support.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Clea Alsip (KATE)</span></b><span style="font-family: garamond"> was born in Tulsa, Oklahoma. She began acting in the second grade and has continued ever since. At Stanford, she is double majoring in International Relations and Drama. For Ram&#8217;s Head she has performed in Gaieties '04 and '05, &#8220;Company,&#8221; and last year&#8217;s &#8220;Cabaret.&#8221; She is thrilled to be up there yet again this year and wants to thank all those who support her unconditionally, namely her mom and the loves of her life: Lee, Laura, Cori, and Liz.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Willi Farrales (BLACK)</span></b><span style="font-family: garamond"> found a passion in singing and the performing arts in elementary school and has been an active singer, actor, and dancer whenever he has had the chance.&nbsp; A junior majoring in Human Biology, he has continued his artistic pursuits with appearances in Ram's Head's 2005 productions, Pinkertons and The Real World: Stanford (Donnie).&nbsp; He has also enjoyed the privilege of singing the national anthem for Stanford basketball and has played roles in student films.&nbsp; He loves this show.&nbsp;And he loves you.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Olivia Harewood (MADELAINE TRUE) </span></b><span style="font-family: garamond">is a sophomore CASA major.&nbsp; You may remember her from The Vagina Monologues, Gaieties 2006: From Cal With Love, last year's Original Winter One Acts, Cabaret, and Gaieties 2005: Kill Julie.&nbsp; Olivia will also be part of Stanford Summer Theater.&nbsp; She is most excited and proud to be directing Gaieties 2007 next fall.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Natalia Duong (MAE)</span></b><span style="font-family: garamond"> is excited to make her Ram&#8217;s Head debut with the inspiring cast, crew, and staff of <i style="mso-bidi-font-style: normal">The Wild Party</i>. She began dancing at the age of 3 and hasn&#8217;t been able to stand still since. Currently a freshman at Stanford, she is also a member of Urban Styles and dv8. Natalia is thankful for the opportunity to do what she loves most: perform.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Rory Everitt (EDDIE)</span></b><span style="font-family: garamond"> is a senior majoring in MS&amp;E. He has immensely enjoyed performing for Stanford audiences through Gaieties '04 and three years of Fleet Street. Before he goes off to work for the Man in NYC next year, he eagerly anticipates this one last chance to get up on that MemAud stage.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Bryan Tan (PHIL D'ARMANO)</span></b><span style="font-family: garamond"> is a former professional singer, television show host and runway model. His Stanford credits include: <i style="mso-bidi-font-style: normal">Tripped!</i> (Trip), <i style="mso-bidi-font-style: normal">Survival of the Fittest</i> (Sean), <i style="mso-bidi-font-style: normal">The Waiting Room</i> (Lucas Rose), <i style="mso-bidi-font-style: normal">Achievers</i> (Murphy), <i style="mso-bidi-font-style: normal">How To Make A Classic</i> (Benny), <i style="mso-bidi-font-style: normal">The Christmas Party </i>(James Matthews), <i style="mso-bidi-font-style: normal">A Crooked Line</i> (George) and <i style="mso-bidi-font-style: normal">GusGus2+</i> (Gus) &#8211; the latter origination earning him a nomination for the John F. Kennedy Center&#8217;s Irene Ryan Acting Award in 2005. He is a proud alumnus of the Stanford Harmonics.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Brian &#8220;Benny&#8221; Eggleston (OSCAR D'ARMANO)</span></b><span style="font-family: garamond"> is thrilled to be appearing in his first Merritt Baer production. His theatrical history at Stanford includes performing in Kiss Me Kate, Gaieties &#8217;03, and Gaieties &#8217;04, as well as choreographing Pinkertons the Musical. He is a senior majoring in Symbolic Systems and coterming in Computer Science. He is ecstatic to be working with the most talented cast on the face of the Earth.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Wade Ray (JACKIE)</span></b><span style="font-family: garamond"> is a junior at Stanford University from East Orange, New Jersey.<span style="mso-spacerun: yes">&nbsp; </span>He has been acting since the second grade, and has been dancing for as long as he could remember.<span style="mso-spacerun: yes">&nbsp; </span>At Stanford, Wade is a member of Jam Pac&#8217;d, a Hip-Hop dance group.<span style="mso-spacerun: yes">&nbsp; </span>He was also in <i style="mso-bidi-font-style: normal">Do the Right Thing</i> as well as <i style="mso-bidi-font-style: normal">Spring Migration</i> last year.<span style="mso-spacerun: yes">&nbsp; </span>He is very excited to be a part of <i style="mso-bidi-font-style: normal">The Wild Party</i> cast, and is thankful for everyone involved in making this experience unforgettable.<span style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Molly Pam (NADINE)</span></b><span style="font-family: garamond"> is freshman ecstatic to be her Rams Head debut as Nadine in <i style="mso-bidi-font-style: normal">The Wild Party</i>.&nbsp; She grew up in the far away town of Menlo Park, where she has been dancing since she was 4.&nbsp; She started acting in elementary school and musicals soon followed.&nbsp; She has appeared in such musicals as Hello, Dolly, Footloose, How to succeed in Business, and Damn Yankees.&nbsp;<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Lea Simon (DOLORES) </span></b><span style="font-family: garamond">is a junior majoring in Symbolic Systems. She is incredibly excited to be part of her second Spring Musical here at Stanford. Previous roles include Jenny in <i>Company</i>, Lily in <i>The Secret Garden</i>, the Mother Abbess in <i>The Sound of Music</i> and the Narrator in <i>Blood Brothers </i>. She would like to thank the entire cast and crew for making this such a wonderful experience.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Luke Taylor (THE NEIGHBOR) </span></b><span style="font-family: garamond">has been passionate about the theater ever since he began going to musicals with his father at age 4. Since then, he has enjoyed working on such shows as <i>Into the Woods</i>, <i>The Suicide</i>, <i>Much Ado About Nothing</i> and notable others. Luke is ecstatic to be making his Stanford theatrical debut with this incredibly talented cast.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Jonah Wieder (DANCE CAPTAIN/SAM)</span></b><span style="font-family: garamond"> is a freshman majoring in English and Drama/Dance. He recently performed in Ram&#8217;s Head&#8217;s <i>Gaieties &#8217;06</i>.<span style="mso-spacerun: yes">&nbsp; </span>He is also a member of Urban Styles and will perform in the Dance Division&#8217;s <i>Spring Migration</i> this spring.<span style="mso-spacerun: yes">&nbsp; </span>He thanks his family, friends, and teachers for their support and love!<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Emily Goldstein (PARTYGOER)</span></b><span style="font-family: garamond"> is making her Stanford theatrical debut as a freshman in <i>The Wild Party.<span style="mso-spacerun: yes">&nbsp; </span></i>Performing as long she can remember&#8212;on stage and even behind the camera&#8212;Emily has trained many years in dance and vocal studies.<span style="mso-spacerun: yes">&nbsp; </span>Emily&#8217;s fondest theatre memories come from the MUNY, the nation&#8217;s largest outdoor professional theatre, where she performed for six summers in her hometown St. Louis.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Lara Sofia Romero (PARTYGOER)</span></b><span style="font-family: garamond"> is thrilled to be participating in her first theatrical production at Stanford. Lara Sofia is a member of Bent Spoon, Stanford's modern dance company and continues to practice ballet and jazz. She would like to thank her family, her friends, and the <i style="mso-bidi-font-style: normal">Wild Party</i> cast for their unending enthusiasm and support. <o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Eric Ruth (PARTYGOER)</span></b><span style="font-family: garamond"> is excited to be making his musical theatre debut in <i>The Wild Party </i>with such an amazing, talented cast. He is currently a sophomore considering a major in Computer Science. Eric would like to thank his loving and supportive family, all his friends, and his girlfriend for always being there for him.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Vaughan Meyer (PARTYGOER)</span></b><span style="font-family: garamond"> first found himself on stage playing a magical owl at age 6, but <i style="mso-bidi-font-style: normal">The Wild Party</i> is his first show in 4 years. He would like to thank his loving parents and brother for their support and the wonderful cast, crew, and staff of the show for reminding him of how great theater can be.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Mackenzie Lee (STORYTELLER)</span></b><span style="font-family: garamond"> is excited to be part of his first ever Ram's Head production! Locally-grown, Mackenzie is a freshman studying International Relations. Recent productions include Humperdinck's <i>Hansel and Gretel</i> and Mozart's <i>Cos&igrave; Fan Tutte </i>with the Peninsula Teen Opera.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Madalyn Radlauer (STORYTELLER)</span></b><span style="font-family: garamond"> is a junior majoring in chemistry.&nbsp; <i style="mso-bidi-font-style: normal">The Wild Party</i> is her first Ram's Head production, although she has been performing with Side by Side and University Singers since her freshman year.&nbsp; Past musical credits include <i>How to Succeed</i>,<i> Fame</i>,&nbsp;<i>The Boyfriend</i>,<i> Forum</i>, and&nbsp;<i>Grease</i>.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Laura Stampler (STORYTELLER) </span></b><span style="font-family: garamond">is a freshman from Los Angeles, California and is thrilled to be a part of Ram&#8217;s Head&#8217;s production of <i style="mso-bidi-font-style: normal">The Wild Party</i>.&nbsp; She has always loved theater and made her Stanford debut in Gaieties 2006: From Cal with Love.<o:p></o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><span style="font-family: garamond"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="margin: 0in 0in 0pt"><b style="mso-bidi-font-weight: normal"><span style="font-family: garamond">Andrea Taylor (STORYTELLER)</span></b><span style="font-family: garamond"> is a freshman excited to be performing in her first Stanford production after doing tech crew for 2006 Gaieties! Growing up in Los Angeles, she was a member of the Silverlake Children's Theater Company before becoming involved in the Marlborough High School Musical Theater program. She thanks her parents, Grandpa, and little sister for always supporting her.</span></p></span>
 
<?php
include "bottom.php";
?>
